-- Oxford 5000にCEFRタグがないcrossover見出し語へ、編集可能な暫定CEFRを付与する。
-- 公式値とは別キーで保持し、Oxford 5000タグがある語には適用しない。
WITH provisional(word_id, level) AS (
  VALUES
    ('awake', 'A2'),

    ('excite', 'B1'),
    ('delight', 'B1'),
    ('amuse', 'B1'),
    ('amaze', 'B1'),
    ('bore', 'B1'),
    ('refresh', 'B1'),
    ('understandable', 'B1'),
    ('foolish', 'B1'),
    ('supposed', 'B1'),
    ('unsure', 'B1'),
    ('elder', 'B1'),
    ('pardon', 'B1'),
    ('scold', 'B1'),
    ('quarrel', 'B1'),
    ('jealous', 'B1'),
    ('unsuitable', 'B1'),
    ('fascinated', 'B1'),
    ('puzzled', 'B1'),
    ('economical', 'B1'),
    ('respectful', 'B1'),
    ('compliment', 'B1'),
    ('fluent', 'B1'),

    ('envy', 'B2'),
    ('hinder', 'B2'),
    ('deceive', 'B2'),
    ('astonish', 'B2'),
    ('startle', 'B2'),
    ('embarrass', 'B2'),
    ('frustrate', 'B2'),
    ('fascinate', 'B2'),
    ('irritate', 'B2'),
    ('disgust', 'B2'),
    ('exhaust', 'B2'),
    ('depress', 'B2'),
    ('thrill', 'B2'),
    ('advisable', 'B2'),
    ('preferable', 'B2'),
    ('considerate', 'B2'),
    ('hesitant', 'B2'),
    ('entitled', 'B2'),
    ('doubtful', 'B2'),
    ('uncertain', 'B2'),
    ('undecided', 'B2'),
    ('contaminate', 'B2'),
    ('dedicate', 'B2'),
    ('beware', 'B2'),
    ('conform', 'B2'),
    ('subscribe', 'B2'),
    ('sympathize', 'B2'),
    ('mingle', 'B2'),
    ('collide', 'B2'),
    ('excel', 'B2'),
    ('glare', 'B2'),
    ('marvel', 'B2'),
    ('inferior', 'B2'),
    ('prone', 'B2'),
    ('resistant', 'B2'),
    ('allergic', 'B2'),
    ('responsive', 'B2'),
    ('accustomed', 'B2'),
    ('addicted', 'B2'),
    ('committed', 'B2'),
    ('incapable', 'B2'),
    ('tolerant', 'B2'),
    ('unfit', 'B2'),
    ('destined', 'B2'),
    ('pessimistic', 'B2'),
    ('abundant', 'B2'),
    ('reliant', 'B2'),
    ('detached', 'B2'),
    ('overwhelmed', 'B2'),
    ('astonished', 'B2'),
    ('disturbed', 'B2'),
    ('industrious', 'B2'),
    ('sociable', 'B2'),
    ('literal', 'B2'),
    ('respectable', 'B2'),
    ('sensational', 'B2'),
    ('invaluable', 'B2'),
    ('priceless', 'B2'),
    ('worthless', 'B2'),
    ('temper', 'B2'),

    ('dissuade', 'C1'),
    ('horrify', 'C1'),
    ('captivate', 'C1'),
    ('intrigue', 'C1'),
    ('resent', 'C1'),
    ('entail', 'C1'),
    ('dread', 'C1'),
    ('imperative', 'C1'),
    ('apt', 'C1'),
    ('fearful', 'C1'),
    ('utter', 'C1'),
    ('furnish', 'C1'),
    ('deviate', 'C1'),
    ('refrain', 'C1'),
    ('revert', 'C1'),
    ('grapple', 'C1'),
    ('tamper', 'C1'),
    ('dispense', 'C1'),
    ('hinge', 'C1'),
    ('dwell', 'C1'),
    ('capitalize', 'C1'),
    ('intrude', 'C1'),
    ('delve', 'C1'),
    ('discriminate', 'C1'),
    ('proportional', 'C1'),
    ('subordinate', 'C1'),
    ('susceptible', 'C1'),
    ('receptive', 'C1'),
    ('devoted', 'C1'),
    ('detrimental', 'C1'),
    ('ignorant', 'C1'),
    ('optimal', 'C1'),
    ('advantageous', 'C1'),
    ('compatible', 'C1'),
    ('adept', 'C1'),
    ('proficient', 'C1'),
    ('deficient', 'C1'),
    ('conditional', 'C1'),
    ('exempt', 'C1'),
    ('sensory', 'C1'),
    ('literate', 'C1'),
    ('bearing', 'C1'),
    ('inference', 'C1'),
    ('resemblance', 'C1'),

    ('stipulate', 'C2'),
    ('decree', 'C2'),
    ('succumb', 'C2'),
    ('allude', 'C2'),
    ('culminate', 'C2'),
    ('contingent', 'C2'),
    ('heed', 'C2')
)
INSERT OR IGNORE INTO tags (word_id, tag_key, tag_value)
SELECT p.word_id, 'cefr_provisional', p.level
FROM provisional p
JOIN words w ON w.id = p.word_id
WHERE EXISTS (
  SELECT 1 FROM list_items li
  WHERE li.list_id = 'crossover-v3' AND li.word_id = p.word_id
)
AND NOT EXISTS (
  SELECT 1 FROM tags official
  WHERE official.word_id = p.word_id AND official.tag_key = 'oxford5000'
);
