-- Group 2: one Section per preposition, small semantic groups as Labels.
-- Keep a complete reversible snapshot of the affected rows before changing placement.
CREATE TABLE idiom_group2_sections_backup AS SELECT * FROM idiom_sections WHERE list_id='crossover-v3' AND group_key='grammar-group-3-prepositions';
CREATE TABLE idiom_group2_entries_backup AS SELECT i.* FROM idioms i JOIN idiom_group2_sections_backup s ON s.list_id=i.list_id AND s.section_key=i.section_key;
CREATE TABLE idiom_group2_plan (id TEXT PRIMARY KEY, section_key TEXT, label_key TEXT, sort_order INTEGER);
INSERT INTO idiom_group2_plan SELECT i.id, i.section_key, substr(i.section_key,5), row_number() OVER (ORDER BY s.sort_order,i.sort_order,i.id) FROM idioms i JOIN idiom_group2_sections_backup s ON s.list_id=i.list_id AND s.section_key=i.section_key;
INSERT INTO idiom_sections (list_id, section_key, subtitle, chapter_key, chapter_subtitle, chapter_order, sort_order, group_key, group_subtitle, group_order)
SELECT list_id,'g12-out-of-persuasion','out of',chapter_key,chapter_subtitle,chapter_order,sort_order+1,group_key,group_subtitle,group_order FROM idiom_group2_sections_backup WHERE section_key='g12-into-persuasion';
UPDATE idiom_sections SET subtitle='in', labels='[{"key": "in-participation", "name": "従事・関与"}]' WHERE list_id='crossover-v3' AND section_key='g12-in-participation';
UPDATE idiom_group2_plan SET section_key='g12-in-participation', label_key='in-participation' WHERE section_key='g12-in-participation';
UPDATE idiom_sections SET subtitle='of', labels='[{"key": "of-notification", "name": "通知・確信"}, {"key": "of-request", "name": "要求"}, {"key": "of-removal", "name": "分離"}, {"key": "of-accusation", "name": "非難"}]' WHERE list_id='crossover-v3' AND section_key='g12-of-notification';
UPDATE idiom_group2_plan SET section_key='g12-of-notification', label_key='of-notification' WHERE section_key='g12-of-notification';
UPDATE idiom_group2_plan SET section_key='g12-of-notification', label_key='of-request' WHERE section_key='g12-of-request';
UPDATE idiom_group2_plan SET section_key='g12-of-notification', label_key='of-removal' WHERE section_key='g12-of-removal';
UPDATE idiom_group2_plan SET section_key='g12-of-notification', label_key='of-accusation' WHERE section_key='g12-of-accusation';
UPDATE idiom_sections SET subtitle='for', labels='[{"key": "for-reason", "name": "理由"}, {"key": "for-exchange", "name": "交換・代用"}, {"key": "for-mistake", "name": "見なし・誤認"}]' WHERE list_id='crossover-v3' AND section_key='g12-for-reason';
UPDATE idiom_group2_plan SET section_key='g12-for-reason', label_key='for-reason' WHERE section_key='g12-for-reason';
UPDATE idiom_group2_plan SET section_key='g12-for-reason', label_key='for-exchange' WHERE section_key='g12-for-exchange';
UPDATE idiom_group2_plan SET section_key='g12-for-reason', label_key='for-mistake' WHERE section_key='g12-for-mistake';
UPDATE idiom_sections SET subtitle='into', labels='[{"key": "into-change", "name": "変化"}, {"key": "into-persuasion", "name": "説得"}]' WHERE list_id='crossover-v3' AND section_key='g12-into-change';
UPDATE idiom_group2_plan SET section_key='g12-into-change', label_key='into-change' WHERE section_key='g12-into-change';
UPDATE idiom_group2_plan SET section_key='g12-into-change', label_key='into-persuasion' WHERE section_key='g12-into-persuasion';
UPDATE idiom_sections SET subtitle='with', labels='[{"key": "with-provision", "name": "供給・装備・授与"}, {"key": "with-provision-unit-2", "name": "交換・委任・共有"}, {"key": "with-connection", "name": "関連付け・比較・同一視"}, {"key": "with-connection-unit-2", "name": "接続・結合・混合"}, {"key": "with-accusation", "name": "非難・告発"}]' WHERE list_id='crossover-v3' AND section_key='g12-with-provision';
UPDATE idiom_group2_plan SET section_key='g12-with-provision', label_key='with-provision' WHERE section_key='g12-with-provision';
UPDATE idiom_group2_plan SET section_key='g12-with-provision', label_key='with-provision-unit-2' WHERE section_key='g12-with-provision-unit-2';
UPDATE idiom_group2_plan SET section_key='g12-with-provision', label_key='with-connection' WHERE section_key='g12-with-connection';
UPDATE idiom_group2_plan SET section_key='g12-with-provision', label_key='with-connection-unit-2' WHERE section_key='g12-with-connection-unit-2';
UPDATE idiom_group2_plan SET section_key='g12-with-provision', label_key='with-accusation' WHERE section_key='g12-with-accusation';
UPDATE idiom_sections SET subtitle='to', labels='[{"key": "to-object", "name": "献身・適応・適用"}, {"key": "to-object-unit-2", "name": "追加・割当・移転・関連"}]' WHERE list_id='crossover-v3' AND section_key='g12-to-object';
UPDATE idiom_group2_plan SET section_key='g12-to-object', label_key='to-object' WHERE section_key='g12-to-object';
UPDATE idiom_group2_plan SET section_key='g12-to-object', label_key='to-object-unit-2' WHERE section_key='g12-to-object-unit-2';
UPDATE idiom_sections SET subtitle='as', labels='[{"key": "as-identity", "name": "判断・見なし"}, {"key": "as-identity-unit-2", "name": "描写・認定・分類"}]' WHERE list_id='crossover-v3' AND section_key='g12-as-identity';
UPDATE idiom_group2_plan SET section_key='g12-as-identity', label_key='as-identity' WHERE section_key='g12-as-identity';
UPDATE idiom_group2_plan SET section_key='g12-as-identity', label_key='as-identity-unit-2' WHERE section_key='g12-as-identity-unit-2';
UPDATE idiom_sections SET subtitle='from', labels='[{"key": "from-distinction", "name": "区別"}, {"key": "from-separation", "name": "分離"}, {"key": "from-protection", "name": "保護・救出"}]' WHERE list_id='crossover-v3' AND section_key='g12-from-distinction';
UPDATE idiom_group2_plan SET section_key='g12-from-distinction', label_key='from-distinction' WHERE section_key='g12-from-distinction';
UPDATE idiom_group2_plan SET section_key='g12-from-distinction', label_key='from-separation' WHERE section_key='g12-from-separation';
UPDATE idiom_group2_plan SET section_key='g12-from-distinction', label_key='from-protection' WHERE section_key='g12-from-protection';
UPDATE idiom_sections SET subtitle='out of', labels='[{"key": "out-of-persuasion", "name": "説得してやめさせる"}]' WHERE list_id='crossover-v3' AND section_key='g12-out-of-persuasion';
UPDATE idiom_group2_plan SET section_key='g12-out-of-persuasion', label_key='out-of-persuasion' WHERE section_key='g12-out-of-persuasion';
UPDATE idiom_group2_plan SET section_key='g12-of-notification', label_key='of-accusation' WHERE id IN (SELECT id FROM idiom_group2_entries_backup WHERE phrase IN ('accuse A of B'));
UPDATE idiom_group2_plan SET section_key='g12-with-provision', label_key='with-accusation' WHERE id IN (SELECT id FROM idiom_group2_entries_backup WHERE phrase IN ('charge A with B','reproach A with B'));
UPDATE idiom_group2_plan SET section_key='g12-for-reason', label_key='for-mistake' WHERE id IN (SELECT id FROM idiom_group2_entries_backup WHERE phrase IN ('take A for B','mistake A for B'));
UPDATE idiom_group2_plan SET section_key='g12-with-provision', label_key='with-provision' WHERE id IN (SELECT id FROM idiom_group2_entries_backup WHERE phrase IN ('feed A with B'));
UPDATE idiom_group2_plan SET section_key='g12-from-distinction', label_key='from-separation' WHERE id IN (SELECT id FROM idiom_group2_entries_backup WHERE phrase IN ('separate A from B','isolate A from B'));
UPDATE idiom_group2_plan SET section_key='g12-from-distinction', label_key='from-protection' WHERE id IN (SELECT id FROM idiom_group2_entries_backup WHERE phrase IN ('protect A from B','rescue A from B','save A from B'));
UPDATE idiom_group2_plan SET section_key='g12-out-of-persuasion', label_key='out-of-persuasion' WHERE id IN (SELECT id FROM idiom_group2_entries_backup WHERE phrase IN ('persuade A out of Ving','talk O out of Ving','reason A out of Ving'));
UPDATE idioms SET section_key=p.section_key,label_key=p.label_key,sort_order=p.sort_order,updated_at=datetime('now') FROM idiom_group2_plan p WHERE idioms.id=p.id;
DELETE FROM idiom_sections WHERE list_id='crossover-v3' AND group_key='grammar-group-3-prepositions' AND section_key NOT IN ('g12-in-participation','g12-of-notification','g12-for-reason','g12-into-change','g12-with-provision','g12-to-object','g12-as-identity','g12-from-distinction','g12-out-of-persuasion') AND NOT EXISTS (SELECT 1 FROM idioms i WHERE i.list_id=idiom_sections.list_id AND i.section_key=idiom_sections.section_key);
DROP TABLE idiom_group2_plan;
