import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { renderWordIllustration, prepareIllustrationsForPrint, startIllustration } from '../../public/shared/illustrations.js';
assert.equal(renderWordIllustration({spelling:'key'},'https://vocab.lrnr.jp'),'');
assert.equal(renderWordIllustration({illustration:{url:'javascript:alert(1)'}},'https://vocab.lrnr.jp'),'');
const rendered=renderWordIllustration({spelling:'key',illustration:{url:'/mcp-viewer/api/illustrations/key/11111111-1111-1111-1111-111111111111.png',meaning:'<重要>"'}},'https://vocab.lrnr.jp');
assert.match(rendered,/https:\/\/vocab.lrnr.jp\/mcp-viewer/);
assert.match(rendered,/&lt;重要&gt;&quot;/);
let decoded=0;
const img={loading:'lazy',decode:async()=>{decoded++}};
await prepareIllustrationsForPrint({querySelectorAll:()=>[img]});
assert.equal(img.loading,'eager');assert.equal(decoded,1);
await assert.rejects(()=>prepareIllustrationsForPrint({querySelectorAll:()=>[{decode:async()=>{throw new Error('missing image')}}]}),/missing image/);
const viewerCss=readFileSync(new URL('../../public/viewer/style.css',import.meta.url),'utf8');
const viewerJs=readFileSync(new URL('../../public/viewer/app.js',import.meta.url),'utf8');
assert.match(viewerCss,/\.entry-illustration\s*\{[^}]*float:\s*right/s);
assert.match(viewerCss,/\.entry-notes\s*\{[^}]*clear:\s*both/s);
assert.match(viewerCss,/@media \(max-width: 600px\) \{\n  \.example-list \{ grid-template-columns: minmax\(0, 1fr\); \}\n\}/);
assert.match(viewerJs,/<div class="entry-notes">[\s\S]*?\$\{derivativesHtml\}[\s\S]*?\$\{notesHtml\}/);
console.log('Illustration viewer: escaping, URL restriction and print image readiness passed');

assert.doesNotMatch(rendered, /<img src=/);
assert.match(rendered, /data-illustration-src=/);
assert.match(rendered, /illustration-placeholder/);
const handlers = {};
const classes = new Set(['is-loading']);
const label = { textContent: '' };
const figure = { classList: { remove: key => classes.delete(key), toggle: (key, enabled) => enabled ? classes.add(key) : classes.delete(key) }, querySelector: () => label };
let deferredUrl = 'https://example.com/image.png';
const deferred = { getAttribute: () => deferredUrl, removeAttribute: () => { deferredUrl = null; }, addEventListener: (event, fn) => { handlers[event] = fn; }, closest: () => figure };
startIllustration(deferred);
assert.equal(deferred.src, 'https://example.com/image.png');
handlers.load();
assert.equal(classes.has('is-loading'), false);
handlers.error();
assert.equal(classes.has('is-error'), true);
assert.equal(label.textContent, '画像を読み込めませんでした');
console.log('Deferred illustration source, placeholder success and failure passed');
