name = "vocab-app"
main = "src/index.js"
compatibility_date = "2024-11-01"

[assets]
directory = "../public"
binding = "ASSETS"

[vars]
# GitHub PagesなどAPIと別オリジンからアクセスするフロントエンドのURLをカンマ区切りで指定。
# 例: "https://ryoxsakai.github.io"
ALLOWED_ORIGINS = "https://ryoxsakai.github.io"

[[d1_databases]]
binding = "DB"
database_name = "vocab-db"
database_id = "5bb1bc51-a169-4686-bc34-97e181d536f6"
